/// Mapa de rutas a permisos requeridos (al menos uno debe estar presente)
const Map<String, List<String>> permissionGates = {
  '/dashboard/products': [
    'Products.Dashboard.View',
    'Products.Articles.View',
    'Products.Articles.List',
    'Products.Admin',
  ],
  '/dashboard/sales': [
    'Sales.Dashboard.View',
    'Sales.Quotes.View',
    'Sales.Quotes.List',
    'Sales.Admin',
  ],
  '/dashboard/marketing': [
    'Marketing.Dashboard.View',
    'Marketing.Campaigns.View',
    'Marketing.Leads.View',
    'Marketing.Admin',
  ],
  '/dashboard/warehouse': [
    'Warehouse.Dashboard.View',
    'Warehouse.Stock.View',
    'Warehouse.Stock.List',
    'Warehouse.Admin',
  ],
  '/dashboard/purchases': [
    'Purchases.Dashboard.View',
    'Purchases.Requests.List',
    'Purchases.Requests.View',
    'Purchases.Admin',
  ],
  '/dashboard/projects': [
    'Projects.Dashboard.View',
    'Projects.Admin',
  ],
  '/dashboard': [
    'Dashboard.Operational.View',
    'Dashboard.General.View',
    'Products.Dashboard.View',
    'Products.Articles.List',
    'Products.Articles.View',
    'Sales.Dashboard.View',
    'Sales.Quotes.List',
    'Sales.Quotes.View',
    'Marketing.Dashboard.View',
    'Marketing.Campaigns.List',
    'Marketing.Leads.List',
    'Warehouse.Dashboard.View',
    'Warehouse.Stock.List',
    'Purchases.Dashboard.View',
    'Purchases.Requests.List',
    'Purchases.Requests.View',
    'Projects.Dashboard.View',
    'Projects.Projects.List',
    'Projects.Projects.View',
  ],
  '/iam/users/new': [
    'IAM.Users.Create',
    'IAM.Invitations.Send',
    'IAM.Users.Admin'
  ],
  '/iam/users': ['IAM.Users.List', 'IAM.Users.View', 'IAM.Users.Admin'],
  '/iam/invitations': ['IAM.Invitations.List', 'IAM.Invitations.Send'],
  '/authorization': ['IAM.Roles.List'],
  '/logs/audit': ['IAM.Audit.List'],
  '/logs/apitraces': ['Logs.ApiTraces.List'],
  '/logs/notifications': ['Logs.NotificationLogs.List'],
  '/admin/tenants/new': [
    'Organization.Tenants.Create',
    'Organization.Admin',
  ],
  '/admin/tenants/': [
    'Organization.Tenants.Edit',
    'Organization.Admin',
  ],
  '/admin/tenants': [
    'Organization.Tenants.List',
    'Organization.Tenants.View',
    'Organization.Listar',
    'Organization.Admin',
  ],
  '/admin/branches': [
    'Organization.Branches.List',
    'Organization.Listar',
    'Organization.Admin',
  ],
  '/organization/sellers/new': [
    'Organization.Sellers.Create',
    'Organization.Admin',
  ],
  '/organization/sellers/': [
    'Organization.Sellers.Edit',
    'Organization.Admin',
  ],
  '/organization/sellers': [
    'Organization.Sellers.List',
    'Organization.Sellers.View',
    'Organization.Admin',
  ],
  '/organization/suppliers/new': [
    'Organization.Suppliers.Create',
    'Organization.Admin',
  ],
  '/organization/suppliers/': [
    'Organization.Suppliers.Edit',
    'Organization.Admin',
  ],
  '/organization/suppliers': [
    'Organization.Suppliers.List',
    'Organization.Suppliers.View',
    'Organization.Admin',
  ],
  '/organization/customers/new': [
    'Organization.Customers.Create',
    'Organization.Admin',
  ],
  '/organization/customers/': [
    'Organization.Customers.Edit',
    'Organization.Admin',
  ],
  '/organization/customers': [
    'Organization.Customers.List',
    'Organization.Customers.View',
    'Organization.Admin',
  ],
  '/people/new': ['People.Create', 'People.Admin'],
  '/people/': ['People.Edit', 'People.Admin'],
  '/people': ['People.List', 'People.View', 'Persona.Ver', 'People.Admin'],
  '/products/import': [
    'Products.Articles.Import',
    'Producto.ImportarProductos',
    'Products.Admin',
  ],
  '/products/new': [
    'Products.Articles.Create',
    'Producto.CrearProducto',
    'Products.Admin',
  ],
  '/products/': [
    'Products.Articles.Edit',
    'Producto.EditarProducto',
    'Products.Admin',
  ],
  '/products': [
    'Products.Articles.List',
    'Products.Articles.View',
    'Producto.VerProducto',
    'Products.Admin',
  ],
  '/sales/quotes': ['Sales.Quotes.List', 'Sales.Quotes.View', 'Sales.Admin'],
  '/purchases/requests': [
    'Purchases.Requests.List',
    'Purchases.Requests.View',
    'Purchases.Admin',
  ],
  '/projects': [
    'Projects.Projects.List',
    'Projects.Projects.View',
    'Projects.Admin',
  ],
  '/projects/types': [
    'Projects.ProjectTypes.List',
    'Projects.ProjectTypes.View',
    'Projects.Admin',
  ],
  '/projects/resources': [
    'Projects.Resources.List',
    'Projects.Resources.View',
    'Projects.Admin',
  ],
  '/projects/templates': [
    'Projects.ProjectTemplates.List',
    'Projects.ProjectTemplates.View',
    'Projects.Admin',
  ],
  '/warehouse/stock': [
    'Warehouse.Stock.List',
    'Warehouse.Stock.View',
    'Warehouse.Admin',
  ],
  '/warehouse/operations': [
    'Warehouse.Locations.List',
    'Warehouse.Reservations.List',
    'Warehouse.ReorderRules.List',
    'Warehouse.Transfers.List',
    'Warehouse.Admin',
    'Warehouse.Editor',
  ],
  '/warehouse': [
    'Warehouse.Warehouses.List',
    'Warehouse.Warehouses.View',
    'Warehouse.Admin',
  ],
  '/marketing/campaigns': [
    'Marketing.Campaigns.List',
    'Marketing.Campaigns.View',
    'Marketing.Campaign.List',
    'Marketing.Campaign.View',
    'Marketing.VerCampanias',
    'Marketing.Admin',
  ],
  '/marketing/coupons': [
    'Marketing.Coupons.List',
    'Marketing.Coupons.View',
    'Marketing.Coupon.List',
    'Marketing.Coupon.View',
    'Marketing.VerCupones',
    'Marketing.Admin',
  ],
  '/marketing/leads': [
    'Marketing.Leads.List',
    'Marketing.Leads.View',
    'Marketing.VerLead',
    'Marketing.Admin',
  ],
  '/marketing/destacados': [
    'Marketing.FeaturedProducts.List',
    'Marketing.FeaturedProducts.View',
    'Marketing.VerDestacados',
    'Marketing.Admin',
  ],
  '/notifications/center': [
    'Notification.Inbox',
    'Notification.Access',
    'Notification.Listar',
    'Notification.Ver',
    'Notification.Admin',
    'Sales.Quotes.List',
    'Sales.Quotes.View',
    'Sales.Admin',
  ],
  '/notifications/types': [
    'Notification.Listar',
    'Notification.Admin',
    'Notificacion.VerTipos'
  ],
  '/notifications/templates': [
    'Notification.Listar',
    'Notification.Admin',
    'Notificacion.VerPlantillas'
  ],
  '/notifications/sender-profiles': [
    'Notification.Listar',
    'Notification.Admin'
  ],
  '/notifications/variables': [
    'Notification.Listar',
    'Notification.Admin',
    'Notificacion.VerPlantillas',
  ],
  '/core/currencies': ['Core.VerMoneda', 'Currencies.Admin'],
  '/core/languages': ['Core.VerIdioma', 'Languages.Admin'],
  '/core/geo/countries': ['Core.VerGeografia', 'Countries.Admin'],
  '/core/geo/states': ['Core.VerGeografia'],
  '/core/geo/cities': ['Core.VerGeografia'],
  '/core/toggles': ['Core.VerToggle', 'Core.Toggles.Admin'],
  '/core/parameters': ['Core.Parameters.Ver'],
};
